version: "3.9"

services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    platform: linux/amd64
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 6
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-changeme}
      POSTGRES_USER: ${DB_USER:-changeme}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    platform: linux/amd64
    environment:
      PGADMIN_DEFAULT_EMAIL: julien@gmail.com
      PGADMIN_DEFAULT_PASSWORD: julien
    ports:
      - "5050:80"
